services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Lukaschel\PimcoreConfigurationBundle\Controller\:
        resource: '../../../Controller'
        public: true
        tags: ['controller.service_arguments']
