services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # bundleconfiguration twig extension
    twig.bundleconfiguration:
        class: Lukaschel\PimcoreConfigurationBundle\Twig\Extension\BundleConfigurationExtension
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }
